"""empty message

Revision ID: 868ef7407ac1
Revises: d381c786b885
Create Date: 2025-12-02 15:20:27.081030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868ef7407ac1'
down_revision = 'd381c786b885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
